#ifndef CONFIG_H
#define CONFIG_H

// Blynk credentials - KEEP THESE SECRET!
#define BLYNK_TEMPLATE_ID "TMPL4f7ASCKOI"
#define BLYNK_TEMPLATE_NAME "beertap"
#define BLYNK_AUTH_TOKEN "YOUR_AUTH_TOKEN_HERE"

// WiFi credentials - KEEP THESE SECRET!
#define WIFI_SSID "YOUR_WIFI_SSID_HERE"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD_HERE"

#endif // CONFIG_H
